### ISSUE TITLE
Notifications are sent several times

### ISSUE THREAD

**Issue by gBasil** [tooot-app/api#8]
When receiving a notification (i.e. a favorite or follow), it shows up several times (around five notifications are sent over the span of several minutes). I'm logged in on two accounts, that's the only change I can think of, as this issue hasn't occurred before then.

**Comment by xmflsct** [comment]
Thanks for the report! Please find the fix in the latest version of tooot https://social.xmflsct.com/@tooot/110910780923847924. And the relevant issue of why https://github.com/tooot-app/app/issues/754.
